apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager
spec:
  hostPath:
    path: /mnt/alertmanager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  hostPath:
    path: /mnt/prometheus
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
