apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  nodeName: worker2
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "1"
    args:
    - -cpus
    - "1"
