apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  nodeName: worker2
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "3Gi"
      limits:
        memory: "4Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "3G", "--vm-hang", "1"]
